In [1]:
import pandas as pd
import numpy as np
import ast
import json
import requests
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import seaborn as sns

from config import api_key

In [2]:
url = 'https://api.themoviedb.org/3/trending/movie/day?api_key='+api_key

In [3]:
r = requests.get(url)
r

In [4]:
json = r.json()
json

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/qK7Ssnrfvrt65F66A1thvehfQg2.jpg',
   'genre_ids': [16, 10751, 35, 12, 14, 9648],
   'id': 420821,
   'original_language': 'en',
   'original_title': "Chip 'n Dale: Rescue Rangers",
   'overview': 'Decades since their successful television series was canceled, Chip has succumbed to a life of suburban domesticity as an insurance salesman. Dale, meanwhile, has had CGI surgery and works the nostalgia convention circuit, desperate to relive his glory days. When a former cast mate mysteriously disappears, Chip and Dale must repair their broken friendship and take on their Rescue Rangers detective personas once again to save their friend’s life.',
   'poster_path': '/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg',
   'release_date': '2022-05-20',
   'title': "Chip 'n Dale: Rescue Rangers",
   'video': False,
   'vote_average': 7.3,
   'vote_count': 36,
   'popularity': 87.881,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg',
   'genre_ids': [28, 878, 14],
   'id': 526896,
   'original_language': 'en',
   'original_title': 'Morbius',
   'poster_path': '/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg',
   'title': 'Morbius',
   'video': False,
   'vote_average': 6.3,
   'overview': 'Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.',
   'release_date': '2022-03-30',
   'vote_count': 938,
   'popularity': 6323.965,
   'media_type': 'movie'},
  {'poster_path': '/tXpLmtnArbGcE75iPJVYibW7BBf.jpg',
   'video': False,
   'vote_average': 7.4,
   'overview': "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
   'release_date': '2022-04-28',
   'vote_count': 31,
   'adult': False,
   'backdrop_path': '/kiH3KPWi7BaRMvdAigcwrUFViHl.jpg',
   'id': 818397,
   'genre_ids': [9648, 53, 28, 80],
   'title': 'Memory',
   'original_language': 'en',
   'original_title': 'Memory',
   'popularity': 118.002,
   'media_type': 'movie'},
  {'title': 'The Valet',
   'vote_average': 6.3,
   'overview': 'World famous movie star Olivia faces a PR disaster when a paparazzi snaps a photo of her with her married lover, Vincent. The hard-working valet Antonio accidentally appears in the same photo and is enlisted to pose as Olivia’s new boyfriend as a cover-up. This ruse with Olivia thrusts Antonio into the spotlight and unexpected chaos.',
   'id': 810171,
   'vote_count': 12,
   'adult': False,
   'backdrop_path': '/kB1Qrsg189eDz4Ej3ABXtLudClq.jpg',
   'video': False,
   'genre_ids': [35],
   'release_date': '2022-05-11',
   'original_language': 'en',
   'original_title': 'The Valet',
   'poster_path': '/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg',
   'popularity': 68.677,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg',
   'genre_ids': [28, 12, 878, 35],
   'id': 545611,
   'original_language': 'en',
   'original_title': 'Everything Everywhere All at Once',
   'overview': "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
   'poster_path': '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
   'release_date': '2022-03-24',
   'title': 'Everything Everywhere All at Once',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 254,
   'popularity': 325.871,
   'media_type': 'movie'},
  {'title': 'Sonic the Hedgehog 2',
   'vote_average': 7.8,
   'overview': 'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
   'id': 675353,
   'vote_count': 1487,
   'adult': False,
   'backdrop_path': '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
   'video': False,
   'genre_ids': [28, 878, 35, 10751, 12],
   'release_date': '2022-03-30',
   'original_language': 'en',
   'original_title': 'Sonic the Hedgehog 2',
   'poster_path': '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
   'popularity': 6201.709,
   'media_type': 'movie'},
  {'video': False,
   'title': 'The Batman',
   'id': 414906,
   'overview': 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
   'release_date': '2022-03-01',
   'adult': False,
   'backdrop_path': '/xHrp2pq73oi9D64xigPjWW1wcz1.jpg',
   'genre_ids': [80, 9648, 53],
   'vote_count': 4672,
   'original_language': 'en',
   'original_title': 'The Batman',
   'poster_path': '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
   'vote_average': 7.8,
   'popularity': 2950.956,
   'media_type': 'movie'},
  {'id': 828853,
   'adult': False,
   'backdrop_path': '/BlC5QrSHnEHFAjAYrLdngUIA8r.jpg',
   'genre_ids': [35, 99, 28],
   'original_language': 'en',
   'original_title': 'Jackass 4.5',
   'poster_path': '/kewHZSdRyOWaLwVwhmoMhjp40Lz.jpg',
   'vote_count': 9,
   'video': False,
   'vote_average': 5.6,
   'title': 'Jackass 4.5',
   'overview': "Through outrageous, never-before-seen footage, witness the making of the Jackass crew's last go at wild stunts.",
   'release_date': '2022-05-20',
   'popularity': 106.149,
   'media_type': 'movie'},
  {'overview': 'To land a major client, an LA wine exec travels to an Australian sheep station, where she signs on as a ranch hand and hits it off with a rugged local.',
   'release_date': '2022-05-19',
   'title': 'A Perfect Pairing',
   'adult': False,
   'backdrop_path': '/6fRVz7ZIZIGFEOq4THY2pdBBhfS.jpg',
   'genre_ids': [35, 10749],
   'original_language': 'en',
   'original_title': 'A Perfect Pairing',
   'poster_path': '/h65lLhYEfRGOWVZzwX9n7vYOixf.jpg',
   'vote_count': 25,
   'video': False,
   'vote_average': 6.7,
   'id': 934761,
   'popularity': 75.39,
   'media_type': 'movie'},
  {'overview': "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
   'release_date': '2022-04-07',
   'adult': False,
   'backdrop_path': '/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg',
   'id': 639933,
   'genre_ids': [28, 12, 14, 53],
   'original_language': 'en',
   'original_title': 'The Northman',
   'poster_path': '/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',
   'vote_count': 974,
   'video': False,
   'vote_average': 7.5,
   'title': 'The Northman',
   'popularity': 5772.331,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/awTRgcAANmco5SaSqoHPHsS5fqZ.jpg',
   'genre_ids': [878, 35, 53],
   'id': 698128,
   'original_language': 'en',
   'original_title': 'Dual',
   'overview': 'A terminally ill woman opts for a cloning procedure to ease her loss on her friends and family. When she makes a miraculous recovery, her attempts to have her clone decommissioned fail and lead to a court-mandated duel to the death.',
   'poster_path': '/wDEse2TQRiyfhdlusSXBdkDOQRj.jpg',
   'release_date': '2022-03-18',
   'title': 'Dual',
   'video': False,
   'vote_average': 6.5,
   'vote_count': 8,
   'popularity': 11.469,
   'media_type': 'movie'},
  {'original_title': 'F*ck De Liefde 2',
   'poster_path': '/u71tsZpPsIK9kTXbxHtSbNr6oSd.jpg',
   'video': True,
   'vote_average': 6.5,
   'overview': 'In this romantic comedy, several friends, each dealing with unhappy love lives, turn to each other for help - but not always with the best results.',
   'release_date': '2022-05-20',
   'title': 'F*ck Love Too',
   'adult': False,
   'id': 970308,
   'vote_count': 2,
   'genre_ids': [35, 10749],
   'backdrop_path': '/nGHpOx23acHMXlkiltwFD9QhbhZ.jpg',
   'original_language': 'nl',
   'popularity': 39.053,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg',
   'genre_ids': [28, 12, 35, 10749],
   'title': 'The Lost City',
   'original_language': 'en',
   'original_title': 'The Lost City',
   'poster_path': '/neMZH82Stu91d3iqvLdNQfqPPyl.jpg',
   'id': 752623,
   'video': False,
   'vote_average': 6.8,
   'overview': 'A reclusive romance novelist who was sure nothing could be worse than getting stuck on a book tour with her cover model, until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.',
   'release_date': '2022-03-24',
   'vote_count': 648,
   'popularity': 8293.346,
   'media_type': 'movie'},
  {'title': 'Doctor Strange in the Multiverse of Madness',
   'overview': 'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
   'release_date': '2022-05-04',
   'adult': False,
   'backdrop_path': '/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
   'vote_count': 1708,
   'genre_ids': [14, 28, 12],
   'vote_average': 7.5,
   'original_language': 'en',
   'original_title': 'Doctor Strange in the Multiverse of Madness',
   'poster_path': '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
   'id': 453395,
   'video': False,
   'popularity': 2713.478,
   'media_type': 'movie'},
  {'original_language': 'en',
   'original_title': 'Spider-Man: No Way Home',
   'id': 634649,
   'video': False,
   'vote_average': 8.1,
   'overview': 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
   'release_date': '2021-12-15',
   'title': 'Spider-Man: No Way Home',
   'adult': False,
   'backdrop_path': '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
   'vote_count': 12901,
   'genre_ids': [28, 12, 878],
   'poster_path': '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
   'popularity': 2676.693,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/fEe5fe82qHzjO4yej0o79etqsWV.jpg',
   'genre_ids': [16, 35, 28, 10751, 80],
   'vote_count': 450,
   'original_language': 'en',
   'original_title': 'The Bad Guys',
   'id': 629542,
   'title': 'The Bad Guys',
   'video': False,
   'vote_average': 7.8,
   'poster_path': '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg',
   'overview': 'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
   'release_date': '2022-03-17',
   'popularity': 2622.506,
   'media_type': 'movie'},
  {'video': False,
   'vote_average': 6.7,
   'overview': "When a Danish chef travels to Tuscany to sell his father's business, he meets a local woman who inspires him to rethink his approach to life and love.",
   'release_date': '2022-05-18',
   'adult': False,
   'backdrop_path': '/6OVV95xVpj8ZcNGVcj40AXdiltM.jpg',
   'vote_count': 13,
   'genre_ids': [35, 10749, 18],
   'title': 'Toscana',
   'original_language': 'da',
   'original_title': 'Toscana',
   'poster_path': '/6itRs4d4RT8EBwBKthPtwV7otLJ.jpg',
   'id': 859585,
   'popularity': 69.486,
   'media_type': 'movie'},
  {'vote_average': 7.2,
   'overview': 'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
   'release_date': '2022-02-10',
   'id': 335787,
   'adult': False,
   'backdrop_path': '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
   'genre_ids': [28, 12],
   'vote_count': 2028,
   'original_language': 'en',
   'original_title': 'Uncharted',
   'poster_path': '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
   'title': 'Uncharted',
   'video': False,
   'popularity': 3187.651,
   'media_type': 'movie'},
  {'poster_path': '/eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg',
   'video': False,
   'vote_average': 6.1,
   'overview': 'Anonymous and exploitative, a network of online chat rooms ran rampant with sex crimes. The hunt to take down its operators required guts and tenacity.',
   'release_date': '2022-05-17',
   'vote_count': 11,
   'adult': False,
   'backdrop_path': '/okUGREWC4LN2TSjFX0AOiNJhzdN.jpg',
   'id': 965143,
   'genre_ids': [99],
   'title': 'Cyber Hell: Exposing an Internet Horror',
   'original_language': 'ko',
   'original_title': '사이버 지옥: n번방을 무너뜨려라',
   'popularity': 73.402,
   'media_type': 'movie'},
  {'release_date': '2022-04-06',
   'adult': False,
   'backdrop_path': '/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg',
   'id': 338953,
   'genre_ids': [28, 12, 14],
   'original_language': 'en',
   'original_title': 'Fantastic Beasts: The Secrets of Dumbledore',
   'poster_path': '/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg',
   'vote_count': 1062,
   'video': False,
   'vote_average': 6.7,
   'title': 'Fantastic Beasts: The Secrets of Dumbledore',
   'overview': "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
   'popularity': 787.576,
   'media_type': 'movie'}],
 'total_pages': 1000,
 'total_results': 20000}

In [5]:
json.keys()

dict_keys(['page', 'results', 'total_pages', 'total_results'])

In [6]:
json['results']

[{'adult': False,
  'backdrop_path': '/qK7Ssnrfvrt65F66A1thvehfQg2.jpg',
  'genre_ids': [16, 10751, 35, 12, 14, 9648],
  'id': 420821,
  'original_language': 'en',
  'original_title': "Chip 'n Dale: Rescue Rangers",
  'overview': 'Decades since their successful television series was canceled, Chip has succumbed to a life of suburban domesticity as an insurance salesman. Dale, meanwhile, has had CGI surgery and works the nostalgia convention circuit, desperate to relive his glory days. When a former cast mate mysteriously disappears, Chip and Dale must repair their broken friendship and take on their Rescue Rangers detective personas once again to save their friend’s life.',
  'poster_path': '/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg',
  'release_date': '2022-05-20',
  'title': "Chip 'n Dale: Rescue Rangers",
  'video': False,
  'vote_average': 7.3,
  'vote_count': 36,
  'popularity': 87.881,
  'media_type': 'movie'},
 {'adult': False,
  'backdrop_path': '/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg',
  'genre_ids': [28, 878, 14],
  'id': 526896,
  'original_language': 'en',
  'original_title': 'Morbius',
  'poster_path': '/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg',
  'title': 'Morbius',
  'video': False,
  'vote_average': 6.3,
  'overview': 'Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.',
  'release_date': '2022-03-30',
  'vote_count': 938,
  'popularity': 6323.965,
  'media_type': 'movie'},
 {'poster_path': '/tXpLmtnArbGcE75iPJVYibW7BBf.jpg',
  'video': False,
  'vote_average': 7.4,
  'overview': "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
  'release_date': '2022-04-28',
  'vote_count': 31,
  'adult': False,
  'backdrop_path': '/kiH3KPWi7BaRMvdAigcwrUFViHl.jpg',
  'id': 818397,
  'genre_ids': [9648, 53, 28, 80],
  'title': 'Memory',
  'original_language': 'en',
  'original_title': 'Memory',
  'popularity': 118.002,
  'media_type': 'movie'},
 {'title': 'The Valet',
  'vote_average': 6.3,
  'overview': 'World famous movie star Olivia faces a PR disaster when a paparazzi snaps a photo of her with her married lover, Vincent. The hard-working valet Antonio accidentally appears in the same photo and is enlisted to pose as Olivia’s new boyfriend as a cover-up. This ruse with Olivia thrusts Antonio into the spotlight and unexpected chaos.',
  'id': 810171,
  'vote_count': 12,
  'adult': False,
  'backdrop_path': '/kB1Qrsg189eDz4Ej3ABXtLudClq.jpg',
  'video': False,
  'genre_ids': [35],
  'release_date': '2022-05-11',
  'original_language': 'en',
  'original_title': 'The Valet',
  'poster_path': '/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg',
  'popularity': 68.677,
  'media_type': 'movie'},
 {'adult': False,
  'backdrop_path': '/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg',
  'genre_ids': [28, 12, 878, 35],
  'id': 545611,
  'original_language': 'en',
  'original_title': 'Everything Everywhere All at Once',
  'overview': "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
  'poster_path': '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
  'release_date': '2022-03-24',
  'title': 'Everything Everywhere All at Once',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 254,
  'popularity': 325.871,
  'media_type': 'movie'},
 {'title': 'Sonic the Hedgehog 2',
  'vote_average': 7.8,
  'overview': 'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
  'id': 675353,
  'vote_count': 1487,
  'adult': False,
  'backdrop_path': '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
  'video': False,
  'genre_ids': [28, 878, 35, 10751, 12],
  'release_date': '2022-03-30',
  'original_language': 'en',
  'original_title': 'Sonic the Hedgehog 2',
  'poster_path': '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
  'popularity': 6201.709,
  'media_type': 'movie'},
 {'video': False,
  'title': 'The Batman',
  'id': 414906,
  'overview': 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
  'release_date': '2022-03-01',
  'adult': False,
  'backdrop_path': '/xHrp2pq73oi9D64xigPjWW1wcz1.jpg',
  'genre_ids': [80, 9648, 53],
  'vote_count': 4672,
  'original_language': 'en',
  'original_title': 'The Batman',
  'poster_path': '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
  'vote_average': 7.8,
  'popularity': 2950.956,
  'media_type': 'movie'},
 {'id': 828853,
  'adult': False,
  'backdrop_path': '/BlC5QrSHnEHFAjAYrLdngUIA8r.jpg',
  'genre_ids': [35, 99, 28],
  'original_language': 'en',
  'original_title': 'Jackass 4.5',
  'poster_path': '/kewHZSdRyOWaLwVwhmoMhjp40Lz.jpg',
  'vote_count': 9,
  'video': False,
  'vote_average': 5.6,
  'title': 'Jackass 4.5',
  'overview': "Through outrageous, never-before-seen footage, witness the making of the Jackass crew's last go at wild stunts.",
  'release_date': '2022-05-20',
  'popularity': 106.149,
  'media_type': 'movie'},
 {'overview': 'To land a major client, an LA wine exec travels to an Australian sheep station, where she signs on as a ranch hand and hits it off with a rugged local.',
  'release_date': '2022-05-19',
  'title': 'A Perfect Pairing',
  'adult': False,
  'backdrop_path': '/6fRVz7ZIZIGFEOq4THY2pdBBhfS.jpg',
  'genre_ids': [35, 10749],
  'original_language': 'en',
  'original_title': 'A Perfect Pairing',
  'poster_path': '/h65lLhYEfRGOWVZzwX9n7vYOixf.jpg',
  'vote_count': 25,
  'video': False,
  'vote_average': 6.7,
  'id': 934761,
  'popularity': 75.39,
  'media_type': 'movie'},
 {'overview': "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
  'release_date': '2022-04-07',
  'adult': False,
  'backdrop_path': '/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg',
  'id': 639933,
  'genre_ids': [28, 12, 14, 53],
  'original_language': 'en',
  'original_title': 'The Northman',
  'poster_path': '/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',
  'vote_count': 974,
  'video': False,
  'vote_average': 7.5,
  'title': 'The Northman',
  'popularity': 5772.331,
  'media_type': 'movie'},
 {'adult': False,
  'backdrop_path': '/awTRgcAANmco5SaSqoHPHsS5fqZ.jpg',
  'genre_ids': [878, 35, 53],
  'id': 698128,
  'original_language': 'en',
  'original_title': 'Dual',
  'overview': 'A terminally ill woman opts for a cloning procedure to ease her loss on her friends and family. When she makes a miraculous recovery, her attempts to have her clone decommissioned fail and lead to a court-mandated duel to the death.',
  'poster_path': '/wDEse2TQRiyfhdlusSXBdkDOQRj.jpg',
  'release_date': '2022-03-18',
  'title': 'Dual',
  'video': False,
  'vote_average': 6.5,
  'vote_count': 8,
  'popularity': 11.469,
  'media_type': 'movie'},
 {'original_title': 'F*ck De Liefde 2',
  'poster_path': '/u71tsZpPsIK9kTXbxHtSbNr6oSd.jpg',
  'video': True,
  'vote_average': 6.5,
  'overview': 'In this romantic comedy, several friends, each dealing with unhappy love lives, turn to each other for help - but not always with the best results.',
  'release_date': '2022-05-20',
  'title': 'F*ck Love Too',
  'adult': False,
  'id': 970308,
  'vote_count': 2,
  'genre_ids': [35, 10749],
  'backdrop_path': '/nGHpOx23acHMXlkiltwFD9QhbhZ.jpg',
  'original_language': 'nl',
  'popularity': 39.053,
  'media_type': 'movie'},
 {'adult': False,
  'backdrop_path': '/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg',
  'genre_ids': [28, 12, 35, 10749],
  'title': 'The Lost City',
  'original_language': 'en',
  'original_title': 'The Lost City',
  'poster_path': '/neMZH82Stu91d3iqvLdNQfqPPyl.jpg',
  'id': 752623,
  'video': False,
  'vote_average': 6.8,
  'overview': 'A reclusive romance novelist who was sure nothing could be worse than getting stuck on a book tour with her cover model, until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.',
  'release_date': '2022-03-24',
  'vote_count': 648,
  'popularity': 8293.346,
  'media_type': 'movie'},
 {'title': 'Doctor Strange in the Multiverse of Madness',
  'overview': 'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
  'release_date': '2022-05-04',
  'adult': False,
  'backdrop_path': '/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
  'vote_count': 1708,
  'genre_ids': [14, 28, 12],
  'vote_average': 7.5,
  'original_language': 'en',
  'original_title': 'Doctor Strange in the Multiverse of Madness',
  'poster_path': '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
  'id': 453395,
  'video': False,
  'popularity': 2713.478,
  'media_type': 'movie'},
 {'original_language': 'en',
  'original_title': 'Spider-Man: No Way Home',
  'id': 634649,
  'video': False,
  'vote_average': 8.1,
  'overview': 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
  'release_date': '2021-12-15',
  'title': 'Spider-Man: No Way Home',
  'adult': False,
  'backdrop_path': '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
  'vote_count': 12901,
  'genre_ids': [28, 12, 878],
  'poster_path': '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
  'popularity': 2676.693,
  'media_type': 'movie'},
 {'adult': False,
  'backdrop_path': '/fEe5fe82qHzjO4yej0o79etqsWV.jpg',
  'genre_ids': [16, 35, 28, 10751, 80],
  'vote_count': 450,
  'original_language': 'en',
  'original_title': 'The Bad Guys',
  'id': 629542,
  'title': 'The Bad Guys',
  'video': False,
  'vote_average': 7.8,
  'poster_path': '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg',
  'overview': 'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
  'release_date': '2022-03-17',
  'popularity': 2622.506,
  'media_type': 'movie'},
 {'video': False,
  'vote_average': 6.7,
  'overview': "When a Danish chef travels to Tuscany to sell his father's business, he meets a local woman who inspires him to rethink his approach to life and love.",
  'release_date': '2022-05-18',
  'adult': False,
  'backdrop_path': '/6OVV95xVpj8ZcNGVcj40AXdiltM.jpg',
  'vote_count': 13,
  'genre_ids': [35, 10749, 18],
  'title': 'Toscana',
  'original_language': 'da',
  'original_title': 'Toscana',
  'poster_path': '/6itRs4d4RT8EBwBKthPtwV7otLJ.jpg',
  'id': 859585,
  'popularity': 69.486,
  'media_type': 'movie'},
 {'vote_average': 7.2,
  'overview': 'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
  'release_date': '2022-02-10',
  'id': 335787,
  'adult': False,
  'backdrop_path': '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
  'genre_ids': [28, 12],
  'vote_count': 2028,
  'original_language': 'en',
  'original_title': 'Uncharted',
  'poster_path': '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
  'title': 'Uncharted',
  'video': False,
  'popularity': 3187.651,
  'media_type': 'movie'},
 {'poster_path': '/eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg',
  'video': False,
  'vote_average': 6.1,
  'overview': 'Anonymous and exploitative, a network of online chat rooms ran rampant with sex crimes. The hunt to take down its operators required guts and tenacity.',
  'release_date': '2022-05-17',
  'vote_count': 11,
  'adult': False,
  'backdrop_path': '/okUGREWC4LN2TSjFX0AOiNJhzdN.jpg',
  'id': 965143,
  'genre_ids': [99],
  'title': 'Cyber Hell: Exposing an Internet Horror',
  'original_language': 'ko',
  'original_title': '사이버 지옥: n번방을 무너뜨려라',
  'popularity': 73.402,
  'media_type': 'movie'},
 {'release_date': '2022-04-06',
  'adult': False,
  'backdrop_path': '/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg',
  'id': 338953,
  'genre_ids': [28, 12, 14],
  'original_language': 'en',
  'original_title': 'Fantastic Beasts: The Secrets of Dumbledore',
  'poster_path': '/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg',
  'vote_count': 1062,
  'video': False,
  'vote_average': 6.7,
  'title': 'Fantastic Beasts: The Secrets of Dumbledore',
  'overview': "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
  'popularity': 787.576,
  'media_type': 'movie'}]

In [7]:
type(json['results'])

list

In [8]:
type(json['results'][0])

dict

In [9]:
df = pd.DataFrame(json['results'])
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,poster_path,release_date,title,video,vote_average,vote_count,popularity,media_type
0,False,/qK7Ssnrfvrt65F66A1thvehfQg2.jpg,"[16, 10751, 35, 12, 14, 9648]",420821,en,Chip 'n Dale: Rescue Rangers,Decades since their successful television seri...,/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg,2022-05-20,Chip 'n Dale: Rescue Rangers,False,7.3,36,87.881,movie
1,False,/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg,"[28, 878, 14]",526896,en,Morbius,"Dangerously ill with a rare blood disorder, an...",/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg,2022-03-30,Morbius,False,6.3,938,6323.965,movie
2,False,/kiH3KPWi7BaRMvdAigcwrUFViHl.jpg,"[9648, 53, 28, 80]",818397,en,Memory,"Alex, an assassin-for-hire, finds that he's be...",/tXpLmtnArbGcE75iPJVYibW7BBf.jpg,2022-04-28,Memory,False,7.4,31,118.002,movie
3,False,/kB1Qrsg189eDz4Ej3ABXtLudClq.jpg,[35],810171,en,The Valet,World famous movie star Olivia faces a PR disa...,/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg,2022-05-11,The Valet,False,6.3,12,68.677,movie
4,False,/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg,"[28, 12, 878, 35]",545611,en,Everything Everywhere All at Once,An aging Chinese immigrant is swept up in an i...,/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg,2022-03-24,Everything Everywhere All at Once,False,8.7,254,325.871,movie
5,False,/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg,"[28, 878, 35, 10751, 12]",675353,en,Sonic the Hedgehog 2,"After settling in Green Hills, Sonic is eager ...",/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg,2022-03-30,Sonic the Hedgehog 2,False,7.8,1487,6201.709,movie
6,False,/xHrp2pq73oi9D64xigPjWW1wcz1.jpg,"[80, 9648, 53]",414906,en,The Batman,"In his second year of fighting crime, Batman u...",/74xTEgt7R36Fpooo50r9T25onhq.jpg,2022-03-01,The Batman,False,7.8,4672,2950.956,movie
7,False,/BlC5QrSHnEHFAjAYrLdngUIA8r.jpg,"[35, 99, 28]",828853,en,Jackass 4.5,"Through outrageous, never-before-seen footage,...",/kewHZSdRyOWaLwVwhmoMhjp40Lz.jpg,2022-05-20,Jackass 4.5,False,5.6,9,106.149,movie
8,False,/6fRVz7ZIZIGFEOq4THY2pdBBhfS.jpg,"[35, 10749]",934761,en,A Perfect Pairing,"To land a major client, an LA wine exec travel...",/h65lLhYEfRGOWVZzwX9n7vYOixf.jpg,2022-05-19,A Perfect Pairing,False,6.7,25,75.390,movie
9,False,/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg,"[28, 12, 14, 53]",639933,en,The Northman,Prince Amleth is on the verge of becoming a ma...,/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg,2022-04-07,The Northman,False,7.5,974,5772.331,movie
10,False,/awTRgcAANmco5SaSqoHPHsS5fqZ.jpg,"[878, 35, 53]",698128,en,Dual,A terminally ill woman opts for a cloning proc...,/wDEse2TQRiyfhdlusSXBdkDOQRj.jpg,2022-03-18,Dual,False,6.5,8,11.469,movie
11,False,/nGHpOx23acHMXlkiltwFD9QhbhZ.jpg,"[35, 10749]",970308,nl,F*ck De Liefde 2,"In this romantic comedy, several friends, each...",/u71tsZpPsIK9kTXbxHtSbNr6oSd.jpg,2022-05-20,F*ck Love Too,True,6.5,2,39.053,movie
12,False,/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg,"[28, 12, 35, 10749]",752623,en,The Lost City,A reclusive romance novelist who was sure noth...,/neMZH82Stu91d3iqvLdNQfqPPyl.jpg,2022-03-24,The Lost City,False,6.8,648,8293.346,movie
13,False,/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg,"[14, 28, 12]",453395,en,Doctor Strange in the Multiverse of Madness,"Doctor Strange, with the help of mystical alli...",/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg,2022-05-04,Doctor Strange in the Multiverse of Madness,False,7.5,1708,2713.478,movie
14,False,/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg,"[28, 12, 878]",634649,en,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg,2021-12-15,Spider-Man: No Way Home,False,8.1,12901,2676.693,movie
15,False,/fEe5fe82qHzjO4yej0o79etqsWV.jpg,"[16, 35, 28, 10751, 80]",629542,en,The Bad Guys,When the infamous Bad Guys are finally caught ...,/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg,2022-03-17,The Bad Guys,False,7.8,450,2622.506,movie
16,False,/6OVV95xVpj8ZcNGVcj40AXdiltM.jpg,"[35, 10749, 18]",859585,da,Toscana,When a Danish chef travels to Tuscany to sell ...,/6itRs4d4RT8EBwBKthPtwV7otLJ.jpg,2022-05-18,Toscana,False,6.7,13,69.486,movie
17,False,/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg,"[28, 12]",335787,en,Uncharted,"A young street-smart, Nathan Drake and his wis...",/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg,2022-02-10,Uncharted,False,7.2,2028,3187.651,movie
18,False,/okUGREWC4LN2TSjFX0AOiNJhzdN.jpg,[99],965143,ko,사이버 지옥: n번방을 무너뜨려라,"Anonymous and exploitative, a network of onlin...",/eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg,2022-05-17,Cyber Hell: Exposing an Internet Horror,False,6.1,11,73.402,movie
19,False,/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg,"[28, 12, 14]",338953,en,Fantastic Beasts: The Secrets of Dumbledore,"Professor Albus Dumbledore knows the powerful,...",/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg,2022-04-06,Fantastic Beasts: The Secrets of Dumbledore,False,6.7,1062,787.576,movie

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              20 non-null     bool
 1   backdrop_path      20 non-null     object
 2   genre_ids          20 non-null     object
 3   id                 20 non-null     int64
 4   original_language  20 non-null     object
 5   original_title     20 non-null     object
 6   overview           20 non-null     object
 7   poster_path        20 non-null     object
 8   release_date       20 non-null     object
 9   title              20 non-null     object
 10  video              20 non-null     bool
 11  vote_average       20 non-null     float64
 12  vote_count         20 non-null     int64
 13  popularity         20 non-null     float64
 14  media_type         20 non-null     object
dtypes: bool(2), float64(2), int64(2), object(9)
memory usage: 2.2+ KB

In [11]:
df.describe()

                  id  vote_average    vote_count   popularity
count      20.000000     20.000000     20.000000    20.000000
mean   662690.750000      7.065000   1363.450000  2125.279550
std    204158.108956      0.770697   2937.699001  2628.517291
min    335787.000000      5.600000      2.000000    11.469000
25%    508520.750000      6.500000     12.750000    74.893000
50%    657643.000000      7.000000    352.000000   556.723500
75%    821011.000000      7.575000   1168.250000  3010.129750
max    970308.000000      8.700000  12901.000000  8293.346000

In [12]:
genres_url = 'https://api.themoviedb.org/3/genre/movie/list?api_key='+api_key

In [13]:
genres_r = requests.get(genres_url)
genres_r

In [14]:
genres_json = genres_r.json()
genres_json

{'genres': [{'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'},
  {'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 80, 'name': 'Crime'},
  {'id': 99, 'name': 'Documentary'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10751, 'name': 'Family'},
  {'id': 14, 'name': 'Fantasy'},
  {'id': 36, 'name': 'History'},
  {'id': 27, 'name': 'Horror'},
  {'id': 10402, 'name': 'Music'},
  {'id': 9648, 'name': 'Mystery'},
  {'id': 10749, 'name': 'Romance'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 10770, 'name': 'TV Movie'},
  {'id': 53, 'name': 'Thriller'},
  {'id': 10752, 'name': 'War'},
  {'id': 37, 'name': 'Western'}]}

In [15]:
genres_json.keys()

dict_keys(['genres'])

In [16]:
genres_df = pd.DataFrame(genres_json['genres'])
genres_df

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [17]:
for _, row in genres_df.iterrows():
    df[row["name"]] = df["genre_ids"].apply(lambda x : 1 if row["id"] in x else 0)

In [18]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,poster_path,release_date,title,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,False,/qK7Ssnrfvrt65F66A1thvehfQg2.jpg,"[16, 10751, 35, 12, 14, 9648]",420821,en,Chip 'n Dale: Rescue Rangers,Decades since their successful television seri...,/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg,2022-05-20,Chip 'n Dale: Rescue Rangers,...,0,0,0,1,0,0,0,0,0,0
1,False,/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg,"[28, 878, 14]",526896,en,Morbius,"Dangerously ill with a rare blood disorder, an...",/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg,2022-03-30,Morbius,...,0,0,0,0,0,1,0,0,0,0
2,False,/kiH3KPWi7BaRMvdAigcwrUFViHl.jpg,"[9648, 53, 28, 80]",818397,en,Memory,"Alex, an assassin-for-hire, finds that he's be...",/tXpLmtnArbGcE75iPJVYibW7BBf.jpg,2022-04-28,Memory,...,0,0,0,1,0,0,0,1,0,0
3,False,/kB1Qrsg189eDz4Ej3ABXtLudClq.jpg,[35],810171,en,The Valet,World famous movie star Olivia faces a PR disa...,/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg,2022-05-11,The Valet,...,0,0,0,0,0,0,0,0,0,0
4,False,/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg,"[28, 12, 878, 35]",545611,en,Everything Everywhere All at Once,An aging Chinese immigrant is swept up in an i...,/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg,2022-03-24,Everything Everywhere All at Once,...,0,0,0,0,0,1,0,0,0,0
5,False,/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg,"[28, 878, 35, 10751, 12]",675353,en,Sonic the Hedgehog 2,"After settling in Green Hills, Sonic is eager ...",/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg,2022-03-30,Sonic the Hedgehog 2,...,0,0,0,0,0,1,0,0,0,0
6,False,/xHrp2pq73oi9D64xigPjWW1wcz1.jpg,"[80, 9648, 53]",414906,en,The Batman,"In his second year of fighting crime, Batman u...",/74xTEgt7R36Fpooo50r9T25onhq.jpg,2022-03-01,The Batman,...,0,0,0,1,0,0,0,1,0,0
7,False,/BlC5QrSHnEHFAjAYrLdngUIA8r.jpg,"[35, 99, 28]",828853,en,Jackass 4.5,"Through outrageous, never-before-seen footage,...",/kewHZSdRyOWaLwVwhmoMhjp40Lz.jpg,2022-05-20,Jackass 4.5,...,0,0,0,0,0,0,0,0,0,0
8,False,/6fRVz7ZIZIGFEOq4THY2pdBBhfS.jpg,"[35, 10749]",934761,en,A Perfect Pairing,"To land a major client, an LA wine exec travel...",/h65lLhYEfRGOWVZzwX9n7vYOixf.jpg,2022-05-19,A Perfect Pairing,...,0,0,0,0,1,0,0,0,0,0
9,False,/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg,"[28, 12, 14, 53]",639933,en,The Northman,Prince Amleth is on the verge of becoming a ma...,/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg,2022-04-07,The Northman,...,0,0,0,0,0,0,0,1,0,0
10,False,/awTRgcAANmco5SaSqoHPHsS5fqZ.jpg,"[878, 35, 53]",698128,en,Dual,A terminally ill woman opts for a cloning proc...,/wDEse2TQRiyfhdlusSXBdkDOQRj.jpg,2022-03-18,Dual,...,0,0,0,0,0,1,0,1,0,0
11,False,/nGHpOx23acHMXlkiltwFD9QhbhZ.jpg,"[35, 10749]",970308,nl,F*ck De Liefde 2,"In this romantic comedy, several friends, each...",/u71tsZpPsIK9kTXbxHtSbNr6oSd.jpg,2022-05-20,F*ck Love Too,...,0,0,0,0,1,0,0,0,0,0
12,False,/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg,"[28, 12, 35, 10749]",752623,en,The Lost City,A reclusive romance novelist who was sure noth...,/neMZH82Stu91d3iqvLdNQfqPPyl.jpg,2022-03-24,The Lost City,...,0,0,0,0,1,0,0,0,0,0
13,False,/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg,"[14, 28, 12]",453395,en,Doctor Strange in the Multiverse of Madness,"Doctor Strange, with the help of mystical alli...",/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg,2022-05-04,Doctor Strange in the Multiverse of Madness,...,0,0,0,0,0,0,0,0,0,0
14,False,/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg,"[28, 12, 878]",634649,en,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg,2021-12-15,Spider-Man: No Way Home,...,0,0,0,0,0,1,0,0,0,0
15,False,/fEe5fe82qHzjO4yej0o79etqsWV.jpg,"[16, 35, 28, 10751, 80]",629542,en,The Bad Guys,When the infamous Bad Guys are finally caught ...,/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg,2022-03-17,The Bad Guys,...,0,0,0,0,0,0,0,0,0,0
16,False,/6OVV95xVpj8ZcNGVcj40AXdiltM.jpg,"[35, 10749, 18]",859585,da,Toscana,When a Danish chef travels to Tuscany to sell ...,/6itRs4d4RT8EBwBKthPtwV7otLJ.jpg,2022-05-18,Toscana,...,0,0,0,0,1,0,0,0,0,0
17,False,/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg,"[28, 12]",335787,en,Uncharted,"A young street-smart, Nathan Drake and his wis...",/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg,2022-02-10,Uncharted,...,0,0,0,0,0,0,0,0,0,0
18,False,/okUGREWC4LN2TSjFX0AOiNJhzdN.jpg,[99],965143,ko,사이버 지옥: n번방을 무너뜨려라,"Anonymous and exploitative, a network of onlin...",/eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg,2022-05-17,Cyber Hell: Exposing an Internet Horror,...,0,0,0,0,0,0,0,0,0,0
19,False,/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg,"[28, 12, 14]",338953,en,Fantastic Beasts: The Secrets of Dumbledore,"Professor Albus Dumbledore knows the powerful,...",/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg,2022-04-06,Fantastic Beasts: The Secrets of Dumbledore,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df["Action"]=df["genre_ids"].apply(lambda x : 1 if 28 in x else 0)
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,poster_path,release_date,title,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,False,/qK7Ssnrfvrt65F66A1thvehfQg2.jpg,"[16, 10751, 35, 12, 14, 9648]",420821,en,Chip 'n Dale: Rescue Rangers,Decades since their successful television seri...,/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg,2022-05-20,Chip 'n Dale: Rescue Rangers,...,0,0,0,1,0,0,0,0,0,0
1,False,/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg,"[28, 878, 14]",526896,en,Morbius,"Dangerously ill with a rare blood disorder, an...",/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg,2022-03-30,Morbius,...,0,0,0,0,0,1,0,0,0,0
2,False,/kiH3KPWi7BaRMvdAigcwrUFViHl.jpg,"[9648, 53, 28, 80]",818397,en,Memory,"Alex, an assassin-for-hire, finds that he's be...",/tXpLmtnArbGcE75iPJVYibW7BBf.jpg,2022-04-28,Memory,...,0,0,0,1,0,0,0,1,0,0
3,False,/kB1Qrsg189eDz4Ej3ABXtLudClq.jpg,[35],810171,en,The Valet,World famous movie star Olivia faces a PR disa...,/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg,2022-05-11,The Valet,...,0,0,0,0,0,0,0,0,0,0
4,False,/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg,"[28, 12, 878, 35]",545611,en,Everything Everywhere All at Once,An aging Chinese immigrant is swept up in an i...,/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg,2022-03-24,Everything Everywhere All at Once,...,0,0,0,0,0,1,0,0,0,0
5,False,/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg,"[28, 878, 35, 10751, 12]",675353,en,Sonic the Hedgehog 2,"After settling in Green Hills, Sonic is eager ...",/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg,2022-03-30,Sonic the Hedgehog 2,...,0,0,0,0,0,1,0,0,0,0
6,False,/xHrp2pq73oi9D64xigPjWW1wcz1.jpg,"[80, 9648, 53]",414906,en,The Batman,"In his second year of fighting crime, Batman u...",/74xTEgt7R36Fpooo50r9T25onhq.jpg,2022-03-01,The Batman,...,0,0,0,1,0,0,0,1,0,0
7,False,/BlC5QrSHnEHFAjAYrLdngUIA8r.jpg,"[35, 99, 28]",828853,en,Jackass 4.5,"Through outrageous, never-before-seen footage,...",/kewHZSdRyOWaLwVwhmoMhjp40Lz.jpg,2022-05-20,Jackass 4.5,...,0,0,0,0,0,0,0,0,0,0
8,False,/6fRVz7ZIZIGFEOq4THY2pdBBhfS.jpg,"[35, 10749]",934761,en,A Perfect Pairing,"To land a major client, an LA wine exec travel...",/h65lLhYEfRGOWVZzwX9n7vYOixf.jpg,2022-05-19,A Perfect Pairing,...,0,0,0,0,1,0,0,0,0,0
9,False,/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg,"[28, 12, 14, 53]",639933,en,The Northman,Prince Amleth is on the verge of becoming a ma...,/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg,2022-04-07,The Northman,...,0,0,0,0,0,0,0,1,0,0
10,False,/awTRgcAANmco5SaSqoHPHsS5fqZ.jpg,"[878, 35, 53]",698128,en,Dual,A terminally ill woman opts for a cloning proc...,/wDEse2TQRiyfhdlusSXBdkDOQRj.jpg,2022-03-18,Dual,...,0,0,0,0,0,1,0,1,0,0
11,False,/nGHpOx23acHMXlkiltwFD9QhbhZ.jpg,"[35, 10749]",970308,nl,F*ck De Liefde 2,"In this romantic comedy, several friends, each...",/u71tsZpPsIK9kTXbxHtSbNr6oSd.jpg,2022-05-20,F*ck Love Too,...,0,0,0,0,1,0,0,0,0,0
12,False,/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg,"[28, 12, 35, 10749]",752623,en,The Lost City,A reclusive romance novelist who was sure noth...,/neMZH82Stu91d3iqvLdNQfqPPyl.jpg,2022-03-24,The Lost City,...,0,0,0,0,1,0,0,0,0,0
13,False,/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg,"[14, 28, 12]",453395,en,Doctor Strange in the Multiverse of Madness,"Doctor Strange, with the help of mystical alli...",/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg,2022-05-04,Doctor Strange in the Multiverse of Madness,...,0,0,0,0,0,0,0,0,0,0
14,False,/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg,"[28, 12, 878]",634649,en,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg,2021-12-15,Spider-Man: No Way Home,...,0,0,0,0,0,1,0,0,0,0
15,False,/fEe5fe82qHzjO4yej0o79etqsWV.jpg,"[16, 35, 28, 10751, 80]",629542,en,The Bad Guys,When the infamous Bad Guys are finally caught ...,/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg,2022-03-17,The Bad Guys,...,0,0,0,0,0,0,0,0,0,0
16,False,/6OVV95xVpj8ZcNGVcj40AXdiltM.jpg,"[35, 10749, 18]",859585,da,Toscana,When a Danish chef travels to Tuscany to sell ...,/6itRs4d4RT8EBwBKthPtwV7otLJ.jpg,2022-05-18,Toscana,...,0,0,0,0,1,0,0,0,0,0
17,False,/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg,"[28, 12]",335787,en,Uncharted,"A young street-smart, Nathan Drake and his wis...",/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg,2022-02-10,Uncharted,...,0,0,0,0,0,0,0,0,0,0
18,False,/okUGREWC4LN2TSjFX0AOiNJhzdN.jpg,[99],965143,ko,사이버 지옥: n번방을 무너뜨려라,"Anonymous and exploitative, a network of onlin...",/eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg,2022-05-17,Cyber Hell: Exposing an Internet Horror,...,0,0,0,0,0,0,0,0,0,0
19,False,/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg,"[28, 12, 14]",338953,en,Fantastic Beasts: The Secrets of Dumbledore,"Professor Albus Dumbledore knows the powerful,...",/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg,2022-04-06,Fantastic Beasts: The Secrets of Dumbledore,...,0,0,0,0,0,0,0,0,0,0

In [20]:
genres_df = pd.DataFrame(genres_json['genres'])
genres_df

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [21]:
nRow, nCol = df.shape
print(f'There are {nRow} rows and {nCol} columns.')

There are 20 rows and 34 columns.

In [22]:
test_url = 'https://api.themoviedb.org/3/trending/movie/week?api_key='+api_key

In [23]:
test_r = requests.get(url)
test_r

In [24]:
test_json = test_r.json()
test_json

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/qK7Ssnrfvrt65F66A1thvehfQg2.jpg',
   'genre_ids': [16, 10751, 35, 12, 14, 9648],
   'id': 420821,
   'original_language': 'en',
   'original_title': "Chip 'n Dale: Rescue Rangers",
   'overview': 'Decades since their successful television series was canceled, Chip has succumbed to a life of suburban domesticity as an insurance salesman. Dale, meanwhile, has had CGI surgery and works the nostalgia convention circuit, desperate to relive his glory days. When a former cast mate mysteriously disappears, Chip and Dale must repair their broken friendship and take on their Rescue Rangers detective personas once again to save their friend’s life.',
   'poster_path': '/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg',
   'release_date': '2022-05-20',
   'title': "Chip 'n Dale: Rescue Rangers",
   'video': False,
   'vote_average': 7.3,
   'vote_count': 36,
   'popularity': 87.881,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg',
   'genre_ids': [28, 878, 14],
   'id': 526896,
   'original_language': 'en',
   'original_title': 'Morbius',
   'poster_path': '/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg',
   'title': 'Morbius',
   'video': False,
   'vote_average': 6.3,
   'overview': 'Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.',
   'release_date': '2022-03-30',
   'vote_count': 938,
   'popularity': 6323.965,
   'media_type': 'movie'},
  {'poster_path': '/tXpLmtnArbGcE75iPJVYibW7BBf.jpg',
   'video': False,
   'vote_average': 7.4,
   'overview': "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
   'release_date': '2022-04-28',
   'vote_count': 31,
   'adult': False,
   'backdrop_path': '/kiH3KPWi7BaRMvdAigcwrUFViHl.jpg',
   'id': 818397,
   'genre_ids': [9648, 53, 28, 80],
   'title': 'Memory',
   'original_language': 'en',
   'original_title': 'Memory',
   'popularity': 118.002,
   'media_type': 'movie'},
  {'title': 'The Valet',
   'vote_average': 6.3,
   'overview': 'World famous movie star Olivia faces a PR disaster when a paparazzi snaps a photo of her with her married lover, Vincent. The hard-working valet Antonio accidentally appears in the same photo and is enlisted to pose as Olivia’s new boyfriend as a cover-up. This ruse with Olivia thrusts Antonio into the spotlight and unexpected chaos.',
   'id': 810171,
   'vote_count': 12,
   'adult': False,
   'backdrop_path': '/kB1Qrsg189eDz4Ej3ABXtLudClq.jpg',
   'video': False,
   'genre_ids': [35],
   'release_date': '2022-05-11',
   'original_language': 'en',
   'original_title': 'The Valet',
   'poster_path': '/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg',
   'popularity': 68.677,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg',
   'genre_ids': [28, 12, 878, 35],
   'id': 545611,
   'original_language': 'en',
   'original_title': 'Everything Everywhere All at Once',
   'overview': "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
   'poster_path': '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
   'release_date': '2022-03-24',
   'title': 'Everything Everywhere All at Once',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 254,
   'popularity': 325.871,
   'media_type': 'movie'},
  {'title': 'Sonic the Hedgehog 2',
   'vote_average': 7.8,
   'overview': 'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
   'id': 675353,
   'vote_count': 1487,
   'adult': False,
   'backdrop_path': '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
   'video': False,
   'genre_ids': [28, 878, 35, 10751, 12],
   'release_date': '2022-03-30',
   'original_language': 'en',
   'original_title': 'Sonic the Hedgehog 2',
   'poster_path': '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
   'popularity': 6201.709,
   'media_type': 'movie'},
  {'video': False,
   'title': 'The Batman',
   'id': 414906,
   'overview': 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
   'release_date': '2022-03-01',
   'adult': False,
   'backdrop_path': '/xHrp2pq73oi9D64xigPjWW1wcz1.jpg',
   'genre_ids': [80, 9648, 53],
   'vote_count': 4672,
   'original_language': 'en',
   'original_title': 'The Batman',
   'poster_path': '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
   'vote_average': 7.8,
   'popularity': 2950.956,
   'media_type': 'movie'},
  {'id': 828853,
   'adult': False,
   'backdrop_path': '/BlC5QrSHnEHFAjAYrLdngUIA8r.jpg',
   'genre_ids': [35, 99, 28],
   'original_language': 'en',
   'original_title': 'Jackass 4.5',
   'poster_path': '/kewHZSdRyOWaLwVwhmoMhjp40Lz.jpg',
   'vote_count': 9,
   'video': False,
   'vote_average': 5.6,
   'title': 'Jackass 4.5',
   'overview': "Through outrageous, never-before-seen footage, witness the making of the Jackass crew's last go at wild stunts.",
   'release_date': '2022-05-20',
   'popularity': 106.149,
   'media_type': 'movie'},
  {'overview': 'To land a major client, an LA wine exec travels to an Australian sheep station, where she signs on as a ranch hand and hits it off with a rugged local.',
   'release_date': '2022-05-19',
   'title': 'A Perfect Pairing',
   'adult': False,
   'backdrop_path': '/6fRVz7ZIZIGFEOq4THY2pdBBhfS.jpg',
   'genre_ids': [35, 10749],
   'original_language': 'en',
   'original_title': 'A Perfect Pairing',
   'poster_path': '/h65lLhYEfRGOWVZzwX9n7vYOixf.jpg',
   'vote_count': 25,
   'video': False,
   'vote_average': 6.7,
   'id': 934761,
   'popularity': 75.39,
   'media_type': 'movie'},
  {'overview': "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
   'release_date': '2022-04-07',
   'adult': False,
   'backdrop_path': '/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg',
   'id': 639933,
   'genre_ids': [28, 12, 14, 53],
   'original_language': 'en',
   'original_title': 'The Northman',
   'poster_path': '/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',
   'vote_count': 974,
   'video': False,
   'vote_average': 7.5,
   'title': 'The Northman',
   'popularity': 5772.331,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/awTRgcAANmco5SaSqoHPHsS5fqZ.jpg',
   'genre_ids': [878, 35, 53],
   'id': 698128,
   'original_language': 'en',
   'original_title': 'Dual',
   'overview': 'A terminally ill woman opts for a cloning procedure to ease her loss on her friends and family. When she makes a miraculous recovery, her attempts to have her clone decommissioned fail and lead to a court-mandated duel to the death.',
   'poster_path': '/wDEse2TQRiyfhdlusSXBdkDOQRj.jpg',
   'release_date': '2022-03-18',
   'title': 'Dual',
   'video': False,
   'vote_average': 6.5,
   'vote_count': 8,
   'popularity': 11.469,
   'media_type': 'movie'},
  {'original_title': 'F*ck De Liefde 2',
   'poster_path': '/u71tsZpPsIK9kTXbxHtSbNr6oSd.jpg',
   'video': True,
   'vote_average': 6.5,
   'overview': 'In this romantic comedy, several friends, each dealing with unhappy love lives, turn to each other for help - but not always with the best results.',
   'release_date': '2022-05-20',
   'title': 'F*ck Love Too',
   'adult': False,
   'id': 970308,
   'vote_count': 2,
   'genre_ids': [35, 10749],
   'backdrop_path': '/nGHpOx23acHMXlkiltwFD9QhbhZ.jpg',
   'original_language': 'nl',
   'popularity': 39.053,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg',
   'genre_ids': [28, 12, 35, 10749],
   'title': 'The Lost City',
   'original_language': 'en',
   'original_title': 'The Lost City',
   'poster_path': '/neMZH82Stu91d3iqvLdNQfqPPyl.jpg',
   'id': 752623,
   'video': False,
   'vote_average': 6.8,
   'overview': 'A reclusive romance novelist who was sure nothing could be worse than getting stuck on a book tour with her cover model, until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.',
   'release_date': '2022-03-24',
   'vote_count': 648,
   'popularity': 8293.346,
   'media_type': 'movie'},
  {'title': 'Doctor Strange in the Multiverse of Madness',
   'overview': 'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
   'release_date': '2022-05-04',
   'adult': False,
   'backdrop_path': '/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
   'vote_count': 1708,
   'genre_ids': [14, 28, 12],
   'vote_average': 7.5,
   'original_language': 'en',
   'original_title': 'Doctor Strange in the Multiverse of Madness',
   'poster_path': '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
   'id': 453395,
   'video': False,
   'popularity': 2713.478,
   'media_type': 'movie'},
  {'original_language': 'en',
   'original_title': 'Spider-Man: No Way Home',
   'id': 634649,
   'video': False,
   'vote_average': 8.1,
   'overview': 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
   'release_date': '2021-12-15',
   'title': 'Spider-Man: No Way Home',
   'adult': False,
   'backdrop_path': '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
   'vote_count': 12901,
   'genre_ids': [28, 12, 878],
   'poster_path': '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
   'popularity': 2676.693,
   'media_type': 'movie'},
  {'adult': False,
   'backdrop_path': '/fEe5fe82qHzjO4yej0o79etqsWV.jpg',
   'genre_ids': [16, 35, 28, 10751, 80],
   'vote_count': 450,
   'original_language': 'en',
   'original_title': 'The Bad Guys',
   'id': 629542,
   'title': 'The Bad Guys',
   'video': False,
   'vote_average': 7.8,
   'poster_path': '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg',
   'overview': 'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
   'release_date': '2022-03-17',
   'popularity': 2622.506,
   'media_type': 'movie'},
  {'video': False,
   'vote_average': 6.7,
   'overview': "When a Danish chef travels to Tuscany to sell his father's business, he meets a local woman who inspires him to rethink his approach to life and love.",
   'release_date': '2022-05-18',
   'adult': False,
   'backdrop_path': '/6OVV95xVpj8ZcNGVcj40AXdiltM.jpg',
   'vote_count': 13,
   'genre_ids': [35, 10749, 18],
   'title': 'Toscana',
   'original_language': 'da',
   'original_title': 'Toscana',
   'poster_path': '/6itRs4d4RT8EBwBKthPtwV7otLJ.jpg',
   'id': 859585,
   'popularity': 69.486,
   'media_type': 'movie'},
  {'vote_average': 7.2,
   'overview': 'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
   'release_date': '2022-02-10',
   'id': 335787,
   'adult': False,
   'backdrop_path': '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
   'genre_ids': [28, 12],
   'vote_count': 2028,
   'original_language': 'en',
   'original_title': 'Uncharted',
   'poster_path': '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
   'title': 'Uncharted',
   'video': False,
   'popularity': 3187.651,
   'media_type': 'movie'},
  {'poster_path': '/eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg',
   'video': False,
   'vote_average': 6.1,
   'overview': 'Anonymous and exploitative, a network of online chat rooms ran rampant with sex crimes. The hunt to take down its operators required guts and tenacity.',
   'release_date': '2022-05-17',
   'vote_count': 11,
   'adult': False,
   'backdrop_path': '/okUGREWC4LN2TSjFX0AOiNJhzdN.jpg',
   'id': 965143,
   'genre_ids': [99],
   'title': 'Cyber Hell: Exposing an Internet Horror',
   'original_language': 'ko',
   'original_title': '사이버 지옥: n번방을 무너뜨려라',
   'popularity': 73.402,
   'media_type': 'movie'},
  {'release_date': '2022-04-06',
   'adult': False,
   'backdrop_path': '/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg',
   'id': 338953,
   'genre_ids': [28, 12, 14],
   'original_language': 'en',
   'original_title': 'Fantastic Beasts: The Secrets of Dumbledore',
   'poster_path': '/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg',
   'vote_count': 1062,
   'video': False,
   'vote_average': 6.7,
   'title': 'Fantastic Beasts: The Secrets of Dumbledore',
   'overview': "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
   'popularity': 787.576,
   'media_type': 'movie'}],
 'total_pages': 1000,
 'total_results': 20000}

In [25]:
test_json.keys()

dict_keys(['page', 'results', 'total_pages', 'total_results'])

In [26]:
test_df = pd.DataFrame(test_json['results'])
test_df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,poster_path,release_date,title,video,vote_average,vote_count,popularity,media_type
0,False,/qK7Ssnrfvrt65F66A1thvehfQg2.jpg,"[16, 10751, 35, 12, 14, 9648]",420821,en,Chip 'n Dale: Rescue Rangers,Decades since their successful television seri...,/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg,2022-05-20,Chip 'n Dale: Rescue Rangers,False,7.3,36,87.881,movie
1,False,/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg,"[28, 878, 14]",526896,en,Morbius,"Dangerously ill with a rare blood disorder, an...",/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg,2022-03-30,Morbius,False,6.3,938,6323.965,movie
2,False,/kiH3KPWi7BaRMvdAigcwrUFViHl.jpg,"[9648, 53, 28, 80]",818397,en,Memory,"Alex, an assassin-for-hire, finds that he's be...",/tXpLmtnArbGcE75iPJVYibW7BBf.jpg,2022-04-28,Memory,False,7.4,31,118.002,movie
3,False,/kB1Qrsg189eDz4Ej3ABXtLudClq.jpg,[35],810171,en,The Valet,World famous movie star Olivia faces a PR disa...,/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg,2022-05-11,The Valet,False,6.3,12,68.677,movie
4,False,/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg,"[28, 12, 878, 35]",545611,en,Everything Everywhere All at Once,An aging Chinese immigrant is swept up in an i...,/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg,2022-03-24,Everything Everywhere All at Once,False,8.7,254,325.871,movie
5,False,/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg,"[28, 878, 35, 10751, 12]",675353,en,Sonic the Hedgehog 2,"After settling in Green Hills, Sonic is eager ...",/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg,2022-03-30,Sonic the Hedgehog 2,False,7.8,1487,6201.709,movie
6,False,/xHrp2pq73oi9D64xigPjWW1wcz1.jpg,"[80, 9648, 53]",414906,en,The Batman,"In his second year of fighting crime, Batman u...",/74xTEgt7R36Fpooo50r9T25onhq.jpg,2022-03-01,The Batman,False,7.8,4672,2950.956,movie
7,False,/BlC5QrSHnEHFAjAYrLdngUIA8r.jpg,"[35, 99, 28]",828853,en,Jackass 4.5,"Through outrageous, never-before-seen footage,...",/kewHZSdRyOWaLwVwhmoMhjp40Lz.jpg,2022-05-20,Jackass 4.5,False,5.6,9,106.149,movie
8,False,/6fRVz7ZIZIGFEOq4THY2pdBBhfS.jpg,"[35, 10749]",934761,en,A Perfect Pairing,"To land a major client, an LA wine exec travel...",/h65lLhYEfRGOWVZzwX9n7vYOixf.jpg,2022-05-19,A Perfect Pairing,False,6.7,25,75.390,movie
9,False,/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg,"[28, 12, 14, 53]",639933,en,The Northman,Prince Amleth is on the verge of becoming a ma...,/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg,2022-04-07,The Northman,False,7.5,974,5772.331,movie
10,False,/awTRgcAANmco5SaSqoHPHsS5fqZ.jpg,"[878, 35, 53]",698128,en,Dual,A terminally ill woman opts for a cloning proc...,/wDEse2TQRiyfhdlusSXBdkDOQRj.jpg,2022-03-18,Dual,False,6.5,8,11.469,movie
11,False,/nGHpOx23acHMXlkiltwFD9QhbhZ.jpg,"[35, 10749]",970308,nl,F*ck De Liefde 2,"In this romantic comedy, several friends, each...",/u71tsZpPsIK9kTXbxHtSbNr6oSd.jpg,2022-05-20,F*ck Love Too,True,6.5,2,39.053,movie
12,False,/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg,"[28, 12, 35, 10749]",752623,en,The Lost City,A reclusive romance novelist who was sure noth...,/neMZH82Stu91d3iqvLdNQfqPPyl.jpg,2022-03-24,The Lost City,False,6.8,648,8293.346,movie
13,False,/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg,"[14, 28, 12]",453395,en,Doctor Strange in the Multiverse of Madness,"Doctor Strange, with the help of mystical alli...",/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg,2022-05-04,Doctor Strange in the Multiverse of Madness,False,7.5,1708,2713.478,movie
14,False,/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg,"[28, 12, 878]",634649,en,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg,2021-12-15,Spider-Man: No Way Home,False,8.1,12901,2676.693,movie
15,False,/fEe5fe82qHzjO4yej0o79etqsWV.jpg,"[16, 35, 28, 10751, 80]",629542,en,The Bad Guys,When the infamous Bad Guys are finally caught ...,/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg,2022-03-17,The Bad Guys,False,7.8,450,2622.506,movie
16,False,/6OVV95xVpj8ZcNGVcj40AXdiltM.jpg,"[35, 10749, 18]",859585,da,Toscana,When a Danish chef travels to Tuscany to sell ...,/6itRs4d4RT8EBwBKthPtwV7otLJ.jpg,2022-05-18,Toscana,False,6.7,13,69.486,movie
17,False,/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg,"[28, 12]",335787,en,Uncharted,"A young street-smart, Nathan Drake and his wis...",/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg,2022-02-10,Uncharted,False,7.2,2028,3187.651,movie
18,False,/okUGREWC4LN2TSjFX0AOiNJhzdN.jpg,[99],965143,ko,사이버 지옥: n번방을 무너뜨려라,"Anonymous and exploitative, a network of onlin...",/eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg,2022-05-17,Cyber Hell: Exposing an Internet Horror,False,6.1,11,73.402,movie
19,False,/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg,"[28, 12, 14]",338953,en,Fantastic Beasts: The Secrets of Dumbledore,"Professor Albus Dumbledore knows the powerful,...",/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg,2022-04-06,Fantastic Beasts: The Secrets of Dumbledore,False,6.7,1062,787.576,movie

In [27]:
tmdb_5000_credits = pd.read_csv('tmdb_5000_credits.csv', delimiter=',')
nRow, nCol = tmdb_5000_credits.shape
print(f'There are {nRow} rows and {nCol} columns.')

There are 4803 rows and 4 columns.

In [28]:
tmdb_5000_credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [29]:
tmdb_5000_credits.describe()

            movie_id
count    4803.000000
mean    57165.484281
std     88694.614033
min         5.000000
25%      9014.500000
50%     14629.000000
75%     58610.500000
max    459488.000000

In [30]:
tmdb_5000_credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [31]:
tmdb_5000_movies = pd.read_csv('tmdb_5000_movies.csv', delimiter=',')
nRow, nCol = tmdb_5000_movies.shape
print(f'There are {nRow} rows and {nCol} columns.')

There are 4803 rows and 20 columns.

In [32]:
tmdb_5000_movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [33]:
keywords=display(tmdb_5000_movies.groupby([tmdb_5000_movies.keywords]).size())
pd.set_option('display.max_rows',50)
print(keywords)

keywords
[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                412
[{"id": 100, "name": "slum"}, {"id": 1009, "name": "baby"}, {"id": 1721, "name": "fight"}, {"id": 2483, "name": "nudity"}, {"id": 3077, "name": "leader"}, {"id": 4339, "name": "johannesburg"}, {"id": 6149, "name": "police"}, {"id": 9673, "name": "love"}, {"id": 9713, "name": "friends"}, {"id": 9826, "name": "murder"}, {"id": 10726, "name": "gang"}, {"id": 13130, "name": "teenager"}, {"id": 14819, "name": "violence"}, {"id": 15009, "name": "criminal"}, {"id": 155238, "name": "hijack"}]                                                                                                                                                                                                                                                                                                                                                           1
[{"id": 100, "name": "slum"}, {"id": 542, "name": "street gang"}, {"id": 2766, "name": "mutation"}, {"id": 3644, "name": "south africa"}, {"id": 4339, "name": "johannesburg"}, {"id": 4565, "name": "dystopia"}, {"id": 6017, "name": "genetics"}, {"id": 6086, "name": "government"}, {"id": 8201, "name": "satire"}, {"id": 9951, "name": "alien"}, {"id": 10650, "name": "prawn"}, {"id": 11800, "name": "mockumentary"}, {"id": 12026, "name": "alternate history"}, {"id": 12425, "name": "racism"}, {"id": 158276, "name": "metamorphosis"}, {"id": 160910, "name": "xenophobia"}, {"id": 195139, "name": "internment camp"}, {"id": 229740, "name": "body transformation"}, {"id": 231277, "name": "alien technology"}, {"id": 233016, "name": "segregation"}]                                                                                              1
[{"id": 100, "name": "slum"}, {"id": 542, "name": "street gang"}, {"id": 699, "name": "love at first sight"}, {"id": 797, "name": "showdown"}, {"id": 2124, "name": "puerto rican"}, {"id": 2356, "name": "immigrant"}, {"id": 3306, "name": "highway"}, {"id": 3691, "name": "forbidden love"}, {"id": 4344, "name": "musical"}, {"id": 9823, "name": "rivalry"}, {"id": 9932, "name": "feud"}, {"id": 10131, "name": "interracial relationship"}, {"id": 10449, "name": "sondheim"}, {"id": 18087, "name": "attempted rape"}, {"id": 33699, "name": "policeman"}, {"id": 158375, "name": "based on stage musical"}, {"id": 159278, "name": "obsessive love"}, {"id": 160367, "name": "lifting female in air"}, {"id": 165100, "name": "young love"}, {"id": 165212, "name": "modern day adaptation"}, {"id": 165214, "name": "shakespeare in modern dress"}]      1
[{"id": 100, "name": "slum"}, {"id": 796, "name": "police brutality"}, {"id": 983, "name": "brazilian"}, {"id": 1601, "name": "war on drugs"}, {"id": 1809, "name": "rio de janeiro"}, {"id": 2149, "name": "drug traffic"}, {"id": 2231, "name": "drug dealer"}, {"id": 7097, "name": "torture by the police"}, {"id": 15218, "name": "special forces"}, {"id": 163081, "name": "law enforcement"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ...
[{"id": 9951, "name": "alien"}, {"id": 163053, "name": "found footage"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
[{"id": 996, "name": "expensive restaurant"}, {"id": 2613, "name": "luxury"}, {"id": 3063, "name": "adolf hitler"}, {"id": 3530, "name": "prague"}, {"id": 9594, "name": "sudetendeutsch"}, {"id": 9736, "name": "little boy"}, {"id": 11064, "name": "nazi germany"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
[{"id": 9963, "name": "kids and family"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
[{"id": 9964, "name": "crude humor"}, {"id": 12392, "name": "best friend"}, {"id": 155761, "name": "phone sex"}, {"id": 204950, "name": "innuendo"}, {"id": 220192, "name": "dirty joke"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
[{"id": 999, "name": "sports car"}, {"id": 1865, "name": "biological weapon"}, {"id": 2106, "name": "cold war"}, {"id": 2808, "name": "russian"}, {"id": 3530, "name": "prague"}, {"id": 10364, "name": "mission"}, {"id": 10456, "name": "athlete"}, {"id": 217142, "name": "nsa agent"}, {"id": 234505, "name": "adrenaline junkie"}, {"id": 234506, "name": "thrill seeker"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Length: 4222, dtype: int64

None

In [34]:
genres=display(tmdb_5000_movies.groupby([tmdb_5000_movies.genres]).size())
pd.set_option('display.max_rows',50)
print(genres)

genres
[]                                                                                                                                                                28
[{"id": 10402, "name": "Music"}, {"id": 10749, "name": "Romance"}]                                                                                                 3
[{"id": 10402, "name": "Music"}, {"id": 12, "name": "Adventure"}, {"id": 16, "name": "Animation"}, {"id": 28, "name": "Action"}, {"id": 35, "name": "Comedy"}]     1
[{"id": 10402, "name": "Music"}, {"id": 18, "name": "Drama"}, {"id": 10749, "name": "Romance"}, {"id": 80, "name": "Crime"}]                                       1
[{"id": 10402, "name": "Music"}, {"id": 18, "name": "Drama"}, {"id": 10749, "name": "Romance"}]                                                                    4
                                                                                                                                                                  ..
[{"id": 99, "name": "Documentary"}, {"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}]                                                                 1
[{"id": 99, "name": "Documentary"}, {"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}]                                                                     1
[{"id": 99, "name": "Documentary"}, {"id": 35, "name": "Comedy"}]                                                                                                  1
[{"id": 99, "name": "Documentary"}, {"id": 36, "name": "History"}]                                                                                                 1
[{"id": 99, "name": "Documentary"}]                                                                                                                               68
Length: 1175, dtype: int64

None

temp=display(tmdb_5000_movies.groupby([tmdb_5000_movies.status]).size())
pd.set_option('display.max_rows',50)
print(temp)

In [35]:
status=display(tmdb_5000_movies.groupby([tmdb_5000_movies.status]).size())
pd.set_option('display.max_rows',50)
print(status)

status
Post Production       3
Released           4795
Rumored               5
dtype: int64

None

In [36]:
tmdb_5000_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [37]:
tmdb_5000_movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [38]:
print("movies dataset shape: ",tmdb_5000_credits.shape)
print("credits dataset shape: ",tmdb_5000_movies.shape)

movies dataset shape:  (4803, 4)
credits dataset shape:  (4803, 20)

In [39]:
movies=tmdb_5000_movies.merge(tmdb_5000_credits,on="title")
movies.head(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576,559,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330,38757,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...",...,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767,99861,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...",...,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293,767,"[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...",...,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004,209112,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."

In [40]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [41]:
movies=movies[["movie_id","genres","title","overview","release_date","keywords","popularity","vote_average","cast","crew","production_companies"]]

In [42]:
movies

,movie_id,genres,title,overview,release_date,keywords,popularity,vote_average,cast,crew,production_companies
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"In the 22nd century, a paraplegic Marine is di...",2009-12-10,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",150.437577,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""name"": ""Ingenious Film Partners"", ""id"": 289..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",2007-05-19,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",139.082615,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,A cryptic message from Bond’s past sends him o...,2015-10-26,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",107.376788,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,Following the death of District Attorney Harve...,2012-07-16,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",112.312950,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""name"": ""Legendary Pictures"", ""id"": 923}, {""..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"John Carter is a war-weary, former military ca...",2012-03-07,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",43.926995,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]"
...,...,...,...,...,...,...,...,...,...,...,...
4804,9367,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi,El Mariachi just wants to play his guitar and ...,1992-09-04,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",14.269792,6.6,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...","[{""name"": ""Columbia Pictures"", ""id"": 5}]"
4805,72766,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",Newlyweds,A newlywed couple's honeymoon is upended by th...,2011-12-26,[],0.642552,5.9,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",[]
4806,231617,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",2013-10-13,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",1.444476,7.0,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","[{""name"": ""Front Street Pictures"", ""id"": 3958}..."
4807,126186,[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,2012-05-03,[],0.857008,5.7,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[]
4808,25975,"[{""id"": 99, ""name"": ""Documentary""}]",My Date with Drew,Ever since the second grade when he first saw ...,2005-08-05,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",1.929883,6.3,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...","[{""name"": ""rusty bear entertainment"", ""id"": 87..."

In [43]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              4809 non-null   int64
 1   genres                4809 non-null   object
 2   title                 4809 non-null   object
 3   overview              4806 non-null   object
 4   release_date          4808 non-null   object
 5   keywords              4809 non-null   object
 6   popularity            4809 non-null   float64
 7   vote_average          4809 non-null   float64
 8   cast                  4809 non-null   object
 9   crew                  4809 non-null   object
 10  production_companies  4809 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 450.8+ KB

In [44]:
movies.isnull().sum()

movie_id                0
genres                  0
title                   0
overview                3
release_date            1
keywords                0
popularity              0
vote_average            0
cast                    0
crew                    0
production_companies    0
dtype: int64

In [45]:
movies.dropna(inplace=True)

In [46]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [47]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i["name"])
    return l

In [48]:
movies["genres"]=movies["genres"].apply(convert)
movies["genres"].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [49]:
movies["keywords"]=movies["keywords"].apply(convert)
movies["keywords"].head()

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

In [50]:
movies["production_companies"]=movies["production_companies"].apply(convert)
movies["production_companies"].head()

0    [Ingenious Film Partners, Twentieth Century Fo...
1    [Walt Disney Pictures, Jerry Bruckheimer Films...
2                     [Columbia Pictures, Danjaq, B24]
3    [Legendary Pictures, Warner Bros., DC Entertai...
4                               [Walt Disney Pictures]
Name: production_companies, dtype: object

In [51]:
movies["cast"][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [52]:
def convert3(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3:
            l.append(i["name"])
            counter+=1
        else:
            break
    return l

In [53]:
movies["cast"]=movies["cast"].apply(convert3)
movies["cast"].head()

0    [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1       [Johnny Depp, Orlando Bloom, Keira Knightley]
2        [Daniel Craig, Christoph Waltz, Léa Seydoux]
3        [Christian Bale, Michael Caine, Gary Oldman]
4      [Taylor Kitsch, Lynn Collins, Samantha Morton]
Name: cast, dtype: object

In [54]:
movies["crew"][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [55]:
def director(obj): 
    l=[]
    for i in ast.literal_eval(obj):
        if i["job"]=="Director":
            l.append(i["name"])
            break
    return l

In [56]:
movies["crew"]=movies["crew"].apply(director)
movies["crew"].head()

0        [James Cameron]
1       [Gore Verbinski]
2           [Sam Mendes]
3    [Christopher Nolan]
4       [Andrew Stanton]
Name: crew, dtype: object

In [57]:
movies["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [58]:
movies["overview"]=movies["overview"].apply(lambda x:x.split())
movies["overview"]

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4805, dtype: object

In [59]:
movies.head()

,movie_id,genres,title,overview,release_date,keywords,popularity,vote_average,cast,crew,production_companies
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",2009-12-10,"[culture clash, future, space war, space colon...",150.437577,7.2,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[Ingenious Film Partners, Twentieth Century Fo..."
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",2007-05-19,"[ocean, drug abuse, exotic island, east india ...",139.082615,6.9,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Walt Disney Pictures, Jerry Bruckheimer Films..."
2,206647,"[Action, Adventure, Crime]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...",2015-10-26,"[spy, based on novel, secret agent, sequel, mi...",107.376788,6.3,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[Columbia Pictures, Danjaq, B24]"
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",2012-07-16,"[dc comics, crime fighter, terrorist, secret i...",112.312950,7.6,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Legendary Pictures, Warner Bros., DC Entertai..."
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...",2012-03-07,"[based on novel, mars, medallion, space travel...",43.926995,6.1,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],[Walt Disney Pictures]

In [60]:
#removing the space from all the columns values.
movies["genres"]=movies["genres"].apply(lambda x:[i.replace(" ","") for i in x])
movies["keywords"]=movies["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
movies["cast"]=movies["cast"].apply(lambda x:[i.replace(" ","") for i in x])
movies["crew"]=movies["crew"].apply(lambda x:[i.replace(" ","") for i in x])
movies.head()

,movie_id,genres,title,overview,release_date,keywords,popularity,vote_average,cast,crew,production_companies
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",2009-12-10,"[cultureclash, future, spacewar, spacecolony, ...",150.437577,7.2,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Ingenious Film Partners, Twentieth Century Fo..."
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",2007-05-19,"[ocean, drugabuse, exoticisland, eastindiatrad...",139.082615,6.9,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Walt Disney Pictures, Jerry Bruckheimer Films..."
2,206647,"[Action, Adventure, Crime]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...",2015-10-26,"[spy, basedonnovel, secretagent, sequel, mi6, ...",107.376788,6.3,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[Columbia Pictures, Danjaq, B24]"
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",2012-07-16,"[dccomics, crimefighter, terrorist, secretiden...",112.312950,7.6,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Legendary Pictures, Warner Bros., DC Entertai..."
4,49529,"[Action, Adventure, ScienceFiction]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...",2012-03-07,"[basedonnovel, mars, medallion, spacetravel, p...",43.926995,6.1,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],[Walt Disney Pictures]

In [61]:
movies["tags"]=movies["overview"]+movies["genres"]+movies["keywords"]+movies["cast"]+movies["crew"]
movies["tags"][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [62]:
new_df=movies[["movie_id","title","tags"]]
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [63]:
#now we need to again convert tag col values into string 
new_df["tags"]=new_df["tags"].apply(lambda x:" ".join(x))
new_df.head()

C:\Users\cellville\AppData\Local\Temp\ipykernel_1000\934411879.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x:" ".join(x))

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [64]:
new_df["tags"]=new_df["tags"].apply(lambda x:x.lower())

C:\Users\cellville\AppData\Local\Temp\ipykernel_1000\4024514323.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x:x.lower())

In [65]:
#use stemmer to create the root word
#ps=PorterStemmer()
from nltk.stem import WordNetLemmatizer

wnl = WordNetLemmatizer()

def x(text):
    y=[]
    for i in text.split():
        y.append(wnl.lemmatize(i)) 
    return " ".join(y)

In [66]:
new_df["tags"]=new_df["tags"].apply(x)
new_df["tags"][0]

LookupError:
**********************************************************************
  Resource omw-1.4 not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('omw-1.4')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/omw-1.4

  Searched in:
    - 'C:\\Users\\cellville/nltk_data'
    - 'C:\\Users\\cellville\\anaconda3\\envs\\PythonData\\nltk_data'
    - 'C:\\Users\\cellville\\anaconda3\\envs\\PythonData\\share\\nltk_data'
    - 'C:\\Users\\cellville\\anaconda3\\envs\\PythonData\\lib\\nltk_data'
    - 'C:\\Users\\cellville\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [67]:
cv=CountVectorizer(max_features=5000,stop_words="english")
X_cv=cv.fit_transform(new_df["tags"]).toarray()
X_cv

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [68]:
#tfidf + n gram (also removes stop words)
#1,2 (1 and 2 word combinations)
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(1,2),stop_words="english")
X_tfidf = vectorizer.fit_transform(new_df.tags.values)
print(X_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [69]:
#pca to vector

In [70]:
# summaalrity score of the ratings (using postlemmetation)
# number of matching words
# number of matching genres/crews/cast
# sentence explaining the movie

# tdif vs count vectorizer: whihc has higher similarity score and use that or average of the both

In [74]:
#calculate the cosine similarity one movie to another movie and get maxium of two arrays + feed into recommendations
# two bc 
#movies name merge and do a comparison
sim_cv=cosine_similarity(X_cv)
sim_tfidf=cosine_similarity(X_tfidf)
print(sim_cv)

[[1.         0.08980265 0.05986843 ... 0.0248452  0.02777778 0.        ]
 [0.08980265 1.         0.06451613 ... 0.02677398 0.         0.        ]
 [0.05986843 0.06451613 1.         ... 0.02677398 0.         0.        ]
 ...
 [0.0248452  0.02677398 0.02677398 ... 1.         0.0745356  0.04774099]
 [0.02777778 0.         0.         ... 0.0745356  1.         0.05337605]
 [0.         0.         0.         ... 0.04774099 0.05337605 1.        ]]

In [75]:
print(sim_tfidf)

[[1.         0.01087611 0.00616873 ... 0.00122235 0.00134975 0.        ]
 [0.01087611 1.         0.00320348 ... 0.00418787 0.         0.        ]
 [0.00616873 0.00320348 1.         ... 0.00379309 0.         0.        ]
 ...
 [0.00122235 0.00418787 0.00379309 ... 1.         0.00627666 0.00776287]
 [0.00134975 0.         0.         ... 0.00627666 1.         0.00397103]
 [0.         0.         0.         ... 0.00776287 0.00397103 1.        ]]

In [76]:
sim_cv.shape

(4805, 4805)

In [77]:
sim_tfidf.shape

(4805, 4805)

In [87]:
# building the movie recommendation function 

def recommend_cv(movie):
    movie_index= new_df[new_df['title']==movie].index[0]
    distance=sim_cv[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [88]:
# lets see the recommendation (seems more accurate)
movies_rec=["Fight Club"]
for i in movies_rec:
    print("If you like:",i)
    print("")
    print("You should watch: \n")
    recommend_cv(i)

If you like: Fight Club

You should watch:

This Is Martin Bonner
Northfork
Never Back Down
Blue Like Jazz
Fight Valley

In [89]:
# building the movie recommendation function 

def recommend_tfidf(movie):
    movie_index= new_df[new_df['title']==movie].index[0]
    distance=sim_tfidf[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [90]:
# lets see the recommendation 
movies_rec=["Fight Club"]
for i in movies_rec:
    print("If you like:",i)
    print("")
    print("You should watch: \n")
    recommend_tfidf(i)

If you like: Fight Club

You should watch:

Never Back Down
Raging Bull
Se7en
What's Eating Gilbert Grape
The Machinist

In [ ]:
# two different algorithms
# drop down with option 1 and option 2 examples (cv & tfdif)
# based on genres, casts, keywords and tags
# text processing (nlp)